const KNOWN_FRAMEWORKS = {
  Malaysia: { framework: 'KSSR Semakan 2017 / KSSM', source: 'Malaysia Ministry of Education curriculum resources', url: 'https://www.moe.gov.my/' },
  'United States': { framework: 'State standards / NGSS', source: 'Next Generation Science Standards', url: 'https://www.nextgenscience.org/' },
  'United Kingdom': { framework: 'National Curriculum for England', source: 'UK Department for Education National Curriculum', url: 'https://www.gov.uk/national-curriculum' },
  Australia: { framework: 'Australian Curriculum v9.0', source: 'Australian Curriculum', url: 'https://www.australiancurriculum.edu.au/f-10-curriculum/' },
  Singapore: { framework: 'Singapore MOE Syllabus', source: 'Singapore Ministry of Education curriculum', url: 'https://www.moe.gov.sg/primary/curriculum' },
  India: { framework: 'NCF-SE 2023 / CBSE', source: 'NCERT National Curriculum Framework', url: 'https://ncert.nic.in/' },
  International: { framework: 'IB PYP / MYP / DP', source: 'International Baccalaureate programme frameworks', url: 'https://www.ibo.org/programmes/' },
};

const escapeHtml = (value = '') => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const words = (topic) => topic.split(/\s+/).filter(Boolean).slice(0, 4);
const label = (value, fallback) => value?.trim() || fallback;

function gradeBand(year) {
  const number = Number((year || '').match(/\d+/)?.[0] || 0);
  if (/preschool|kindergarten|reception|foundation|prasekolah/i.test(year)) return 'primary';
  if (number >= 10 || /form [4-6]|tingkatan [4-6]|a.?level|stpm|ib/i.test(year)) return 'upper_secondary';
  if (number >= 7 || /form [1-3]|tingkatan [1-3]/i.test(year)) return 'lower_secondary';
  return 'primary';
}

export function buildGlobalDemo({ subject, year, topic, language, country, curriculumStandard, studentPersona }) {
  const profile = KNOWN_FRAMEWORKS[country] || null;
  const framework = curriculumStandard || profile?.framework || 'International teacher-review framework';
  const source = curriculumStandard ? 'Teacher-provided curriculum standard (review required)' : profile?.source || 'Teacher-selected country or region (review required)';
  const confidenceLevel = curriculumStandard ? 'inferred' : profile ? 'inferred' : 'general';
  const terms = [...new Set([topic, ...words(topic), `${subject} vocabulary`, `${topic} application`])].slice(0, 6);
  const concepts = [`the central ideas in ${topic}`, `${subject} vocabulary`, 'evidence and examples', 'application to a familiar context'];
  const objectives = [
    `Identify key ideas and vocabulary connected to ${topic}.`,
    `Explain one example or representation of ${topic} using ${subject} language.`,
    `Apply understanding of ${topic} to a teacher-selected local context.`,
  ];
  const questions = Array.from({ length: 8 }, (_, index) => {
    const term = terms[index % terms.length];
    const correct = index % 2 ? `An example connected to ${topic}` : `A key idea from ${topic}`;
    return { id: index + 1, question: `Which response best supports learning about ${term}?`, options: [correct, 'An unrelated idea', 'A copied answer without explanation', 'No evidence or example'], correct, explanation: `Use the teacher's selected material to confirm the best example for ${term}.` };
  });
  const pairs = terms.map((term, index) => ({ id: index + 1, term, definition: `Teacher-review definition or example for ${term} in ${language}.` }));
  const worksheetItems = terms.map((term, index) => ({ id: index + 1, question: `Write, draw, or explain one accurate example of ${term}.`, answer: `Teacher review: accept evidence-based examples connected to ${topic}.`, hint: `Use the lesson notes and the selected ${framework} context.` }));
  const safeTopic = escapeHtml(topic);
  const worksheet = `<div class="worksheet"><h2>${safeTopic} — Teacher-editable demo worksheet</h2><p>Framework: ${escapeHtml(framework)}. Review and adapt before classroom use.</p>${worksheetItems.map((item) => `<p>${item.id}. ${escapeHtml(item.question)}</p>`).join('')}</div>`;
  return {
    status: 'complete', model: 'deterministic-global-demo', demo_mode: true,
    source_notice: `Offline demo starter requested for ${language}. ${profile ? `${profile.framework} is named from its official framework source;` : 'No verified national framework is claimed;'} the deterministic teaching template is in English and requires teacher adaptation or translation before use.`,
    lesson: {
      objectives, key_concepts: concepts, misconceptions: [`Treating ${topic} as a list of facts without explaining evidence.`, 'Using a familiar example that does not match the key concept.'], difficulty: 'intermediate', summary: `A teacher-editable ${subject} lesson starter for ${year} on ${topic}. It uses ${framework} as context and must be reviewed against local materials.`, prerequisite_knowledge: ['Relevant prior vocabulary', 'One familiar example or experience'], real_world_connections: [`A local example chosen by the teacher`, `A classroom discussion connected to ${topic}`], curriculum_alignment: curriculumStandard || `Framework-level alignment only: ${framework}`, curriculum_source: source, confidenceLevel, persona_notes: `Adapt tasks, language load, and scaffolds for ${studentPersona || 'On-Level'} learners.`, grade_band: gradeBand(year), experience_design: { primary_activity: 'quiz', secondary_activity: 'matching', why_primary_activity: 'Use the quiz as a teacher-reviewed retrieval check.', why_quiz: 'It surfaces vocabulary and concept gaps.', why_matching: 'It helps connect terms with teacher-approved examples.', rationale: 'This deterministic demo provides an editable starting structure rather than claiming generated subject facts.', quiz_focus: `Key terms and examples for ${topic}`, matching_focus: `Vocabulary for ${topic}`, difficulty_calibration: `Teacher-adjusted for ${year}`, engagement_strategy: 'Use local examples selected by the teacher.', confidence_score: 60 },
    },
    resources: { quiz: { data: { type: 'mcq', title: `${topic} — Review Quiz`, questions }, engineConfig: { title: `${topic} — Review Quiz`, questions, type: 'mcq' } }, matching: { data: { type: 'drag_drop', title: `${topic} — Vocabulary Match`, pairs }, engineConfig: { title: `${topic} — Vocabulary Match`, instruction: 'Match each term to a teacher-reviewed definition or example.', pairs, type: 'drag_drop' } }, worksheet: { html: worksheet }, answer_key: { html: `<div class="answer-key"><h2>${safeTopic} — Teacher review notes</h2><p>Use teacher-approved examples and the selected framework before marking student work.</p></div>` } },
    teaching_insights: { misconceptions: [{ mistake: `Learners may repeat words about ${topic} without explaining their meaning.`, correction: 'Ask for an example, evidence, or representation.', example: 'Model one teacher-approved local example first.' }], teaching_tips: ['Confirm the exact curriculum standard with the official source before teaching.', 'Replace generic prompts with local examples and class materials.', 'Offer a visual, spoken, and written response option.'], daily_examples: [`A local example selected by the teacher`, `A familiar situation connected to ${topic}`], intervention_strategy: 'Pre-teach key vocabulary and use a worked example.', extension_activity: 'Ask learners to compare two examples and justify which better fits the key concept.', estimated_class_difficulty: 'moderate', time_estimate_minutes: 45, differentiation_note: `Provide sentence stems and visuals for support; ask advanced learners to justify evidence in ${language}.` },
    lesson_evaluation: { scores: { learning_coverage: 65, student_engagement: 68, difficulty_balance: 65, blooms_taxonomy: 60 }, overall_score: 65, grade: 'B', strengths: ['Accepts the selected country, subject, grade, topic, and language without an AI provider.', 'Clearly identifies the curriculum-confidence boundary.'], weaknesses: ['Teacher review is required for factual content and exact standard alignment.'], suggestion: 'Add a teacher-approved source or exact official standard before classroom delivery.', blooms_levels_present: ['Remember', 'Understand', 'Apply'], blooms_levels_missing: ['Evaluate', 'Create'] },
    study_materials: { flashcards: { title: `${topic} — Teacher-review flashcards`, cards: terms.map((term, index) => ({ id: index + 1, front: term, back: `Teacher-review explanation for ${term} in ${language}.`, curriculum_code: curriculumStandard || framework, emoji: '📌' })) }, study_notes: { title: `${topic} — Lesson notes`, subtitle: `${year} · ${subject}`, grade_band_label: year, sections: [{ heading: 'Learning focus', content: `Use teacher-approved materials to explore ${topic}.`, key_points: objectives }, { heading: 'Curriculum check', content: `Framework context: ${framework}. ${source}.`, key_points: ['Confirm the official standard code.', 'Adapt examples for the class.', 'Review language accessibility.'] }] }, mock_exam: { title: `${topic} — Teacher-editable practice`, exam_board: source, format_style: 'Teacher-editable curriculum practice', duration_minutes: 30, total_marks: 20, grade_band: year, questions: worksheetItems.slice(0, 4).map((item) => ({ ...item, section: 'Teacher review', marks: 5, expected_answer: item.answer, rubric: 'Award marks using teacher-approved success criteria.', question_type: 'short_answer' })) }, cloze_passage: { title: `${topic} — Vocabulary review`, passage: `In this lesson, learners explore ___(1)___ in ${subject}. They use evidence, examples, and clear vocabulary to explain ___(2)___.`, blanks: [{ id: 1, word: topic, hint: 'The selected lesson topic' }, { id: 2, word: topic, hint: 'The selected lesson topic' }, { id: 3, word: 'evidence', hint: 'Information that supports an explanation' }] }, study_map: { title: `Learning pathway: ${topic}`, description: 'Teacher-editable pathway; confirm content against official materials.', root: { id: 'root', label: topic, type: 'root', children: concepts.slice(0, 3).map((concept, index) => ({ id: `topic-${index + 1}`, label: concept, description: `Teacher-review focus for ${concept}.`, learning_goal: `Explain ${concept} with an example.`, example: 'Use a locally appropriate example.', check_question: `What evidence supports ${concept}?`, type: 'topic', children: [] })) } }, study_schedule: { title: `${topic} — 4-step study plan`, persona: studentPersona || 'On-Level', total_weeks: 1, total_lessons: 4, overview: 'Review each activity with teacher-approved content before use.', schedule: ['Vocabulary warm-up', 'Teacher model', 'Guided practice', 'Reflection and feedback'].map((activity, index) => ({ time: `Lesson ${index + 1}`, activity, resource: index < 2 ? 'Study notes and flashcards' : 'Quiz and worksheet', duration_minutes: 30, persona_note: 'Adjust scaffolds and challenge for the learner profile.' })), differentiation: { beginner: 'Use visuals and sentence stems.', on_level: 'Explain one example using evidence.', gifted: 'Compare two examples and justify a conclusion.', sen_support: 'Chunk tasks and offer spoken response options.' } } },
    analytics: { generation_time_ms: 0, agent_calls: 0, resources_created: 10, estimated_time_saved_minutes: 60, model: 'deterministic-global-demo', source_confidence: confidenceLevel },
  };
}
