// EduForge AI — i18n Translations
// English + Bahasa Melayu Malaysia
// Global version — any teacher, any country, any curriculum

export const translations = {
  en: {
    // Nav
    brand: 'EduForge AI',
    tagline: 'The AI Teaching Operating System',

    // Home Hero
    hero_headline: 'The AI that thinks\nlike your best teacher.',
    hero_sub: 'Describe your lesson topic. EduForge AI analyses the curriculum, designs the perfect learning experience, creates interactive activities — and evaluates its own work.',
    upload_label: 'Upload Lesson Material',
    upload_hint: 'PDF or TXT — any lesson plan, textbook page, or notes',
    upload_or: 'or describe your lesson',
    upload_limit_title: 'This file is too large to upload',
    upload_limit_notice: '{name} is above the 4 MB upload limit.',
    upload_limit_search: 'Search for material',
    field_material_link: 'Material link',
    demo_scenarios_label: 'Verified demo scenarios',
    demo_scenarios: { ngss: 'Grade 5 Science: States of Matter', kssm: 'Form 1 Sains: Keadaan Jirim', aqa: 'Year 10 History: Norman Conquest' },
    material_link_placeholder: 'Public PDF, TXT, or web page link',
    material_search_label: 'Find exact curriculum material',

    // Form fields
    field_country: 'Country / Region',
    field_curriculum: 'Curriculum Standard (optional)',
    field_subject: 'Subject',
    field_year: 'Grade / Year',
    field_topic: 'Lesson Topic',
    field_language: 'Language of Instruction',
    field_persona: 'Class Profile',
    field_objectives: 'Learning Objectives (optional)',
    objectives_placeholder: 'e.g. Students can identify the three states of matter and explain particle behaviour',
    curriculum_placeholder: 'e.g. Common Core, GCSE, IB, KSSR, Cambridge…',
    topic_placeholder: 'e.g. States of Matter, The Norman Conquest, Fractions…',
    generate_btn: 'Generate Teaching Materials',

    // Country quick-select
    country_quickselect: 'Quick select:',
    country_other: 'Other / International',

    // Student Persona
    persona_beginner: '🌱 Beginner',
    persona_mixed: '🔀 Mixed Ability',
    persona_onlevel: '⭐ On-Level',
    persona_gifted: '🚀 Gifted & Talented',
    persona_sen: '💚 SEN Support',

    // How it works
    how_title: 'How It Works',
    step1: 'Describe your lesson topic and class',
    step2: '5 AI agents analyse, design, and build your materials',
    step3: 'AI evaluates its own work with a quality score',
    step4: 'You get classroom-ready resources in under a minute',

    // Generation Progress — cinematic messages per agent
    progress_title: 'Building Your Lesson...',
    step_curriculum: 'Curriculum Intelligence',
    step_curriculum_msg: 'Analysing learning objectives and detecting student misconceptions...',
    step_experience: 'Experience Designer',
    step_experience_msg: 'Choosing the optimal learning strategy for your class...',
    step_content: 'Content Generator',
    step_content_msg: 'Writing quiz questions, matching pairs, and worksheet items...',
    step_teacher: 'Teacher Assistant',
    step_teacher_msg: 'Preparing teaching insights and intervention strategies...',
    step_evaluator: 'Lesson Evaluator',
    step_evaluator_msg: 'AI is reviewing its own work and scoring the lesson quality...',
    progress_quote: '"Education is not the filling of a pail, but the lighting of a fire." — W.B. Yeats',

    // Dashboard
    dashboard_title: 'Your Teaching Materials',
    dashboard_sub: 'Generated by 5 AI Agents · Designed for teachers worldwide',
    analytics_time: 'Generated in',
    analytics_agents: 'AI Agents',
    analytics_resources: 'Resources',
    analytics_saved: 'Teacher Time Saved',
    analytics_minutes: 'min',
    resource_quiz: 'Interactive Quiz',
    resource_matching: 'Matching Game',
    resource_worksheet: 'Worksheet',
    resource_answerkey: 'Answer Key',
    btn_play: 'Launch Activity',
    btn_download: 'Download',
    btn_print: 'Print',
    questions_count: 'questions',
    pairs_count: 'pairs',
    items_count: 'items',

    // AI Rationale
    rationale_title: 'Why did AI choose this?',
    rationale_subtitle: 'Pedagogical reasoning from the Experience Designer agent',
    confidence_label: 'Strategy Confidence',

    // Lesson Quality Score
    quality_title: 'Lesson Quality Score',
    quality_subtitle: 'AI self-evaluation — Agent 5 reviewing Agents 1–4',
    quality_coverage: 'Learning Coverage',
    quality_engagement: 'Student Engagement',
    quality_difficulty: 'Difficulty Balance',
    quality_blooms: "Bloom's Taxonomy",
    quality_overall: 'Overall Score',
    quality_strengths: 'Strengths',
    quality_weaknesses: 'Areas to Improve',
    quality_suggestion: 'AI Suggestion',
    quality_blooms_present: "Bloom's Levels Present",
    quality_blooms_missing: 'Missing',
    quality_disclaimer: 'AI-generated — review before class',

    // Teaching Insights
    insights_title: 'AI Teaching Insights',
    insights_sub: 'Personalised for your class by Teacher Assistant agent',
    misconceptions_title: 'Common Student Mistakes',
    tips_title: 'Teaching Tips',
    examples_title: 'Real-Life Classroom Examples',
    intervention_title: 'Intervention Strategy',
    extension_title: 'Extension Activity',
    difficulty_label: 'Lesson Difficulty',
    time_label: 'Estimated Duration',
    minutes: 'minutes',
    differentiation_label: 'Differentiation Note',
    new_lesson_btn: '+ New Lesson',
    ai_review_disclaimer: 'AI-generated content — please review before use in class',

    // Curriculum confidence
    confidence_high: 'Adapted for',
    confidence_inferred: 'Inferred from context',
    confidence_general: 'General framework used',

    // Game Preview
    close_preview: 'Close',
    fullscreen: 'Fullscreen',

    // Countries (quick-select row)
    countries: [
      { code: 'MY', name: 'Malaysia', flag: '🇲🇾', curriculum: 'KSSR / KSSM', gradeSystem: 'malaysian' },
      { code: 'US', name: 'United States', flag: '🇺🇸', curriculum: 'Common Core', gradeSystem: 'us' },
      { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', curriculum: 'National Curriculum', gradeSystem: 'uk' },
      { code: 'AU', name: 'Australia', flag: '🇦🇺', curriculum: 'Australian Curriculum', gradeSystem: 'uk' },
      { code: 'SG', name: 'Singapore', flag: '🇸🇬', curriculum: 'MOE Singapore', gradeSystem: 'sg' },
      { code: 'IN', name: 'India', flag: '🇮🇳', curriculum: 'CBSE / ICSE', gradeSystem: 'india' },
      { code: 'INTL', name: 'International / IB', flag: '🌍', curriculum: 'IB / Cambridge', gradeSystem: 'ib' },
    ],

    // Grade systems
    gradeSystems: {
      malaysian: ['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6', 'Form 1', 'Form 2', 'Form 3', 'Form 4', 'Form 5'],
      us: ['Kindergarten', 'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6', 'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12'],
      uk: ['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6', 'Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11', 'Year 12', 'Year 13'],
      sg: ['Primary 1', 'Primary 2', 'Primary 3', 'Primary 4', 'Primary 5', 'Primary 6', 'Secondary 1', 'Secondary 2', 'Secondary 3', 'Secondary 4', 'JC 1', 'JC 2'],
      india: ['Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6', 'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12'],
      ib: ['Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6', 'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12'],
      custom: [],
    },

    // Subjects (global)
    subjects: ['Science', 'Mathematics', 'English', 'History', 'Geography', 'Biology', 'Chemistry', 'Physics', 'Computer Science', 'Art & Design', 'Music', 'Physical Education', 'Economics', 'Business Studies', 'Literature', 'Psychology', 'Sociology', 'Religious Studies', 'Bahasa Melayu', 'French', 'Spanish', 'Mandarin', 'Arabic', 'Other'],

    // Languages (chips)
    languages: ['English', 'Bahasa Melayu', 'Mandarin', 'French', 'Spanish', 'Arabic', 'Tamil', 'Hindi'],

    // Difficulty
    difficulty_easy: 'Easy',
    difficulty_moderate: 'Moderate',
    difficulty_challenging: 'Challenging',

    // Errors
    error_fields: 'Please fill in Subject, Grade/Year, and Topic.',
    error_generate: 'Generation failed. Please try again.',
    error_upload: 'File upload failed. Please try again.',

    // Footer
    footer: 'Built with Codex and GPT-5.6 · OpenAI Build Week 2026 · Designed for teachers worldwide',
  },

  bm: {
    // Nav
    brand: 'EduForge AI',
    tagline: 'Sistem Pengendalian Pengajaran AI',

    // Home Hero
    hero_headline: 'AI yang berfikir seperti\nguru terbaik anda.',
    hero_sub: 'Nyatakan tajuk pelajaran anda. EduForge AI menganalisis kurikulum, mereka bentuk pengalaman pembelajaran terbaik, mencipta aktiviti interaktif — dan menilai kerjanya sendiri.',
    upload_label: 'Muat Naik Bahan Pelajaran',
    upload_hint: 'PDF atau TXT — pelan pelajaran, halaman buku teks, atau nota',
    upload_or: 'atau nyatakan pelajaran anda',
    upload_limit_title: 'Fail ini terlalu besar untuk dimuat naik',
    upload_limit_notice: '{name} melebihi had muat naik 4 MB.',
    upload_limit_search: 'Cari bahan',
    field_material_link: 'Pautan bahan',
    demo_scenarios_label: 'Senario demo disahkan',
    demo_scenarios: { ngss: 'Gred 5 Sains: States of Matter', kssm: 'Tingkatan 1 Sains: Keadaan Jirim', aqa: 'Tahun 10 Sejarah: Norman Conquest' },
    material_link_placeholder: 'Pautan PDF, TXT atau laman web awam',
    material_search_label: 'Cari bahan kurikulum yang tepat',

    // Form fields
    field_country: 'Negara / Rantau',
    field_curriculum: 'Standard Kurikulum (pilihan)',
    field_subject: 'Mata Pelajaran',
    field_year: 'Gred / Tahun',
    field_topic: 'Tajuk Pelajaran',
    field_language: 'Bahasa Pengajaran',
    field_persona: 'Profil Kelas',
    field_objectives: 'Objektif Pembelajaran (pilihan)',
    objectives_placeholder: 'cth. Murid dapat mengenal pasti tiga keadaan jirim dan menerangkan tingkah laku zarah',
    curriculum_placeholder: 'cth. KSSR, Common Core, GCSE, IB, Cambridge…',
    topic_placeholder: 'cth. Keadaan Jirim, Bentuk-bentuk Tenaga, Pecahan…',
    generate_btn: 'Jana Bahan Pengajaran',

    // Country quick-select
    country_quickselect: 'Pilih pantas:',
    country_other: 'Lain-lain / Antarabangsa',

    // Student Persona
    persona_beginner: '🌱 Pemula',
    persona_mixed: '🔀 Pelbagai Kebolehan',
    persona_onlevel: '⭐ Tahap Biasa',
    persona_gifted: '🚀 Berbakat',
    persona_sen: '💚 Keperluan Khas',

    // How it works
    how_title: 'Cara Ia Berfungsi',
    step1: 'Nyatakan tajuk pelajaran dan kelas anda',
    step2: '5 ejen AI menganalisis, mereka bentuk, dan membina bahan anda',
    step3: 'AI menilai kerjanya sendiri dengan skor kualiti',
    step4: 'Anda mendapat bahan siap untuk kelas dalam masa kurang seminit',

    // Generation Progress
    progress_title: 'Membina Pelajaran Anda...',
    step_curriculum: 'Kecerdasan Kurikulum',
    step_curriculum_msg: 'Menganalisis objektif pembelajaran dan mengesan salah faham murid...',
    step_experience: 'Pereka Pengalaman',
    step_experience_msg: 'Memilih strategi pembelajaran optimum untuk kelas anda...',
    step_content: 'Penjana Kandungan',
    step_content_msg: 'Menulis soalan kuiz, padanan, dan lembaran kerja...',
    step_teacher: 'Pembantu Guru',
    step_teacher_msg: 'Menyediakan panduan pengajaran dan strategi intervensi...',
    step_evaluator: 'Penilai Pelajaran',
    step_evaluator_msg: 'AI sedang menilai kerjanya sendiri dan mengehadkan kualiti pelajaran...',
    progress_quote: '"Pendidikan bukan sekadar mengisi baldi, tetapi menyalakan api semangat."',

    // Dashboard
    dashboard_title: 'Bahan Pengajaran Anda',
    dashboard_sub: 'Dijana oleh 5 Ejen AI · Direka untuk guru di seluruh dunia',
    analytics_time: 'Dijana dalam',
    analytics_agents: 'Ejen AI',
    analytics_resources: 'Sumber',
    analytics_saved: 'Masa Guru Dijimatkan',
    analytics_minutes: 'min',
    resource_quiz: 'Kuiz Interaktif',
    resource_matching: 'Permainan Padanan',
    resource_worksheet: 'Lembaran Kerja',
    resource_answerkey: 'Skim Jawapan',
    btn_play: 'Lancar Aktiviti',
    btn_download: 'Muat Turun',
    btn_print: 'Cetak',
    questions_count: 'soalan',
    pairs_count: 'padanan',
    items_count: 'soalan',

    // AI Rationale
    rationale_title: 'Mengapa AI memilih ini?',
    rationale_subtitle: 'Alasan pedagogi daripada ejen Pereka Pengalaman',
    confidence_label: 'Keyakinan Strategi',

    // Lesson Quality Score
    quality_title: 'Skor Kualiti Pelajaran',
    quality_subtitle: 'Penilaian kendiri AI — Ejen 5 menilai Ejen 1–4',
    quality_coverage: 'Liputan Pembelajaran',
    quality_engagement: 'Penglibatan Murid',
    quality_difficulty: 'Keseimbangan Kesukaran',
    quality_blooms: 'Taksonomi Bloom',
    quality_overall: 'Skor Keseluruhan',
    quality_strengths: 'Kekuatan',
    quality_weaknesses: 'Kawasan untuk Diperbaiki',
    quality_suggestion: 'Cadangan AI',
    quality_blooms_present: 'Aras Bloom yang Ada',
    quality_blooms_missing: 'Tidak Ada',
    quality_disclaimer: 'Dijana AI — semak sebelum digunakan dalam kelas',

    // Teaching Insights
    insights_title: 'Panduan Pengajaran AI',
    insights_sub: 'Diperibadikan untuk kelas anda oleh ejen Pembantu Guru',
    misconceptions_title: 'Kesilapan Lazim Murid',
    tips_title: 'Tip Pengajaran',
    examples_title: 'Contoh Kehidupan Sebenar',
    intervention_title: 'Strategi Intervensi',
    extension_title: 'Aktiviti Tambahan',
    difficulty_label: 'Tahap Kesukaran',
    time_label: 'Anggaran Masa',
    minutes: 'minit',
    differentiation_label: 'Nota Pembezaan',
    new_lesson_btn: '+ Pelajaran Baru',
    ai_review_disclaimer: 'Kandungan dijana AI — sila semak sebelum digunakan dalam kelas',

    // Curriculum confidence
    confidence_high: 'Disesuaikan untuk',
    confidence_inferred: 'Disimpulkan daripada konteks',
    confidence_general: 'Rangka kerja umum digunakan',

    // Game Preview
    close_preview: 'Tutup',
    fullscreen: 'Skrin Penuh',

    // Countries (same structure)
    countries: [
      { code: 'MY', name: 'Malaysia', flag: '🇲🇾', curriculum: 'KSSR / KSSM', gradeSystem: 'malaysian' },
      { code: 'US', name: 'Amerika Syarikat', flag: '🇺🇸', curriculum: 'Common Core', gradeSystem: 'us' },
      { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', curriculum: 'National Curriculum', gradeSystem: 'uk' },
      { code: 'AU', name: 'Australia', flag: '🇦🇺', curriculum: 'Australian Curriculum', gradeSystem: 'uk' },
      { code: 'SG', name: 'Singapura', flag: '🇸🇬', curriculum: 'MOE Singapura', gradeSystem: 'sg' },
      { code: 'IN', name: 'India', flag: '🇮🇳', curriculum: 'CBSE / ICSE', gradeSystem: 'india' },
      { code: 'INTL', name: 'Antarabangsa / IB', flag: '🌍', curriculum: 'IB / Cambridge', gradeSystem: 'ib' },
    ],

    // Grade systems (same)
    gradeSystems: {
      malaysian: ['Tahun 1', 'Tahun 2', 'Tahun 3', 'Tahun 4', 'Tahun 5', 'Tahun 6', 'Tingkatan 1', 'Tingkatan 2', 'Tingkatan 3', 'Tingkatan 4', 'Tingkatan 5'],
      us: ['Kindergarten', 'Gred 1', 'Gred 2', 'Gred 3', 'Gred 4', 'Gred 5', 'Gred 6', 'Gred 7', 'Gred 8', 'Gred 9', 'Gred 10', 'Gred 11', 'Gred 12'],
      uk: ['Tahun 1', 'Tahun 2', 'Tahun 3', 'Tahun 4', 'Tahun 5', 'Tahun 6', 'Tahun 7', 'Tahun 8', 'Tahun 9', 'Tahun 10', 'Tahun 11', 'Tahun 12', 'Tahun 13'],
      sg: ['Darjah 1', 'Darjah 2', 'Darjah 3', 'Darjah 4', 'Darjah 5', 'Darjah 6', 'Menengah 1', 'Menengah 2', 'Menengah 3', 'Menengah 4', 'JC 1', 'JC 2'],
      india: ['Gred 1', 'Gred 2', 'Gred 3', 'Gred 4', 'Gred 5', 'Gred 6', 'Gred 7', 'Gred 8', 'Gred 9', 'Gred 10', 'Gred 11', 'Gred 12'],
      ib: ['Gred 1', 'Gred 2', 'Gred 3', 'Gred 4', 'Gred 5', 'Gred 6', 'Gred 7', 'Gred 8', 'Gred 9', 'Gred 10', 'Gred 11', 'Gred 12'],
      custom: [],
    },

    // Subjects
    subjects: ['Sains', 'Matematik', 'Bahasa Melayu', 'Bahasa Inggeris', 'Sejarah', 'Geografi', 'Biologi', 'Kimia', 'Fizik', 'Sains Komputer', 'Pendidikan Seni Visual', 'Muzik', 'Pendidikan Jasmani', 'Ekonomi', 'Perniagaan', 'Sastera', 'Pendidikan Islam', 'Pendidikan Moral', 'Mandarin', 'Bahasa Arab', 'Lain-lain'],

    // Languages
    languages: ['Bahasa Melayu', 'English', 'Mandarin', 'Bahasa Arab', 'Tamil', 'Hindi', 'French', 'Spanish'],

    // Difficulty
    difficulty_easy: 'Mudah',
    difficulty_moderate: 'Sederhana',
    difficulty_challenging: 'Mencabar',

    // Errors
    error_fields: 'Sila isi Mata Pelajaran, Tahun, dan Tajuk.',
    error_generate: 'Jana gagal. Sila cuba lagi.',
    error_upload: 'Muat naik fail gagal. Sila cuba lagi.',

    // Footer
    footer: 'Dibina dengan Codex dan GPT-5.6 · OpenAI Build Week 2026 · Direka untuk guru di seluruh dunia',
  },
};
