// EduForge AI — i18n Translations
// English + Bahasa Melayu Malaysia — complete bilingual UI

export const translations = {
  en: {
    // Nav
    brand: 'EduForge AI',
    tagline: 'AI Teaching Companion',

    // Home
    hero_headline: 'What do you want your\nstudents to learn today?',
    hero_sub: 'Upload a lesson or describe your topic. EduForge AI creates interactive activities in seconds.',
    upload_label: 'Upload Lesson Material',
    upload_hint: 'PDF or TXT file supported',
    upload_or: 'or describe your topic',
    field_subject: 'Subject',
    field_year: 'Year / Form',
    field_topic: 'Topic',
    field_language: 'Content Language',
    field_objectives: 'Learning Objectives (optional)',
    objectives_placeholder: 'e.g. Students can identify types of energy and their uses',
    generate_btn: 'Generate Teaching Materials',
    how_title: 'How EduForge AI Works',
    step1: 'You upload or describe your topic',
    step2: 'GPT-5.6 analyses the curriculum',
    step3: 'Codex builds interactive games',
    step4: 'You get classroom-ready materials',

    // Generation Progress
    progress_title: 'Generating Your Materials...',
    step_curriculum: 'Analysing Curriculum',
    step_experience: 'Designing Learning Experience',
    step_content: 'Generating Activities',
    step_teacher: 'Preparing Teaching Insights',
    progress_quote: '"Education is not the filling of a pail, but the lighting of a fire." — W.B. Yeats',

    // Dashboard
    dashboard_title: 'Your Teaching Materials',
    dashboard_sub: 'Generated by GPT-5.6 · Powered by Codex',
    resource_quiz: 'Interactive Quiz',
    resource_matching: 'Matching Game',
    resource_worksheet: 'Worksheet',
    resource_answerkey: 'Answer Key',
    btn_play: 'Try It',
    btn_download: 'Download',
    questions_count: 'questions',
    pairs_count: 'pairs',
    items_count: 'items',
    insights_title: 'AI Teaching Insights',
    insights_sub: 'GPT-5.6 analysis for this lesson',
    misconceptions_title: 'Common Student Mistakes',
    tips_title: 'Teaching Tips',
    examples_title: 'Malaysian Real-Life Examples',
    intervention_title: 'Intervention Strategy',
    extension_title: 'Extension Activity',
    difficulty_label: 'Lesson Difficulty',
    time_label: 'Estimated Duration',
    minutes: 'minutes',
    new_lesson_btn: '+ New Lesson',
    time_saved: 'Time saved vs manual preparation:',
    time_saved_pct: '99.3%',

    // Game Preview
    close_preview: 'Close',
    fullscreen: 'Fullscreen',

    // Subjects
    subjects: ['Science', 'Mathematics', 'Bahasa Melayu', 'English', 'History', 'Geography', 'Islamic Studies', 'Moral Studies', 'Art', 'Music', 'Physical Education'],

    // Years
    years: ['Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6', 'Form 1', 'Form 2', 'Form 3', 'Form 4', 'Form 5'],

    // Languages
    languages: ['English', 'Bahasa Melayu', 'Mandarin'],

    // Difficulty
    difficulty_mudah: 'Easy',
    difficulty_sederhana: 'Moderate',
    difficulty_sukar: 'Challenging',

    // Errors
    error_fields: 'Please fill in Subject, Year, and Topic.',
    error_generate: 'Generation failed. Please check your API key and try again.',
    error_upload: 'File upload failed. Please try again.',

    // Footer
    footer: 'Built with GPT-5.6 + Codex · OpenAI Build Week 2026',
  },

  bm: {
    // Nav
    brand: 'EduForge AI',
    tagline: 'Pembantu Pengajaran AI',

    // Home
    hero_headline: 'Apa yang anda mahu\nmurid pelajari hari ini?',
    hero_sub: 'Muat naik bahan pelajaran atau nyatakan tajuk anda. EduForge AI mencipta aktiviti interaktif dalam masa beberapa saat.',
    upload_label: 'Muat Naik Bahan Pelajaran',
    upload_hint: 'Fail PDF atau TXT disokong',
    upload_or: 'atau nyatakan tajuk anda',
    field_subject: 'Mata Pelajaran',
    field_year: 'Tahun / Tingkatan',
    field_topic: 'Tajuk',
    field_language: 'Bahasa Kandungan',
    field_objectives: 'Objektif Pembelajaran (pilihan)',
    objectives_placeholder: 'cth. Murid dapat mengenal pasti jenis-jenis tenaga dan kegunaannya',
    generate_btn: 'Jana Bahan Pengajaran',
    how_title: 'Cara EduForge AI Berfungsi',
    step1: 'Anda muat naik atau nyatakan tajuk',
    step2: 'GPT-5.6 menganalisis kurikulum',
    step3: 'Codex membina permainan interaktif',
    step4: 'Anda mendapat bahan siap untuk kelas',

    // Generation Progress
    progress_title: 'Sedang Menjana Bahan Anda...',
    step_curriculum: 'Menganalisis Kurikulum',
    step_experience: 'Mereka Bentuk Pengalaman Pembelajaran',
    step_content: 'Menjana Aktiviti',
    step_teacher: 'Menyediakan Panduan Pengajaran',
    progress_quote: '"Pendidikan bukan sekadar mengisi baldi, tetapi menyalakan api semangat."',

    // Dashboard
    dashboard_title: 'Bahan Pengajaran Anda',
    dashboard_sub: 'Dijana oleh GPT-5.6 · Dikuasakan oleh Codex',
    resource_quiz: 'Kuiz Interaktif',
    resource_matching: 'Permainan Padanan',
    resource_worksheet: 'Lembaran Kerja',
    resource_answerkey: 'Skim Jawapan',
    btn_play: 'Cuba Main',
    btn_download: 'Muat Turun',
    questions_count: 'soalan',
    pairs_count: 'padanan',
    items_count: 'soalan',
    insights_title: 'Panduan Pengajaran AI',
    insights_sub: 'Analisis GPT-5.6 untuk pelajaran ini',
    misconceptions_title: 'Kesilapan Lazim Murid',
    tips_title: 'Tip Pengajaran',
    examples_title: 'Contoh Kehidupan Harian Malaysia',
    intervention_title: 'Strategi Intervensi',
    extension_title: 'Aktiviti Tambahan (Murid Laju)',
    difficulty_label: 'Tahap Kesukaran Pelajaran',
    time_label: 'Anggaran Masa',
    minutes: 'minit',
    new_lesson_btn: '+ Pelajaran Baru',
    time_saved: 'Masa yang jimat berbanding persediaan manual:',
    time_saved_pct: '99.3%',

    // Game Preview
    close_preview: 'Tutup',
    fullscreen: 'Skrin Penuh',

    // Subjects
    subjects: ['Sains', 'Matematik', 'Bahasa Melayu', 'Bahasa Inggeris', 'Sejarah', 'Geografi', 'Pendidikan Islam', 'Pendidikan Moral', 'Pendidikan Seni Visual', 'Muzik', 'Pendidikan Jasmani'],

    // Years
    years: ['Tahun 1', 'Tahun 2', 'Tahun 3', 'Tahun 4', 'Tahun 5', 'Tahun 6', 'Tingkatan 1', 'Tingkatan 2', 'Tingkatan 3', 'Tingkatan 4', 'Tingkatan 5'],

    // Languages
    languages: ['Bahasa Melayu', 'English', 'Mandarin'],

    // Difficulty
    difficulty_mudah: 'Mudah',
    difficulty_sederhana: 'Sederhana',
    difficulty_sukar: 'Sukar',

    // Errors
    error_fields: 'Sila isi Mata Pelajaran, Tahun, dan Tajuk.',
    error_generate: 'Jana gagal. Sila semak kunci API anda dan cuba lagi.',
    error_upload: 'Muat naik fail gagal. Sila cuba lagi.',

    // Footer
    footer: 'Dibina dengan GPT-5.6 + Codex · OpenAI Build Week 2026',
  },
};
